{% set version = "0.3.0" %}

package:
  name: r-httpcode
  version: {{ version }}

source:
  fn: httpcode_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/httpcode_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/httpcode/httpcode_{{ version }}.tar.gz
  sha256: 593a030a4f94c3df8c15576837c17344701bac023ae108783d0f06c476062f76

build:
  number: 2
  script: 'R CMD INSTALL --build . ${R_ARGS}'  # [not win]
  script: R CMD INSTALL --build . ${R_ARGS}  # [win]
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('httpcode')"  # [not win]
    - "\"%R%\" -e \"library('httpcode')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/httpcode
  license: MIT
  license_file: LICENSE
  summary: Find and explain the meaning of 'HTTP' status codes. Functions included for searching for codes by full or partial number, by message, and get appropriate
    dog and cat images for many status codes.

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
