travis:
  secure:
    BINSTAR_TOKEN: rT89a3dFUMLq6DPRb8ewfIPg0peAtCBWtpOoxBXSsrNkAFYnHEDiv3wJ9aPlHPH0GIsBLuoAW4b6Qn89jxkI4OQIg+jCKDaqk9+Px+R1/gwsbg33j9tgw60s/Or9AWxqvj8zy6gv6UqcFonvsJV5Lgp4538JDBX5MrxRINnFYXTIurm//ghwEJsJC4eTOXgbGH6w2RCyOXeD5vnpfGOjSrPjWXI28DbS0i8X7NNJ7cIAyJbIt3pcMekOhWIjpCDdNwQVbyw8V1VSniHWnq1ETC4r84zlx8rixnoK2NUbd772cI6oMeTEO9dgJgT1ziLagABSrwBFQIGGW7B9tMmvEGKJPoCIgI+ury9kG++2iL1vsMWrbKNeH62r4RdnFAe4aNEn9zLQ4eMiYII73+/ebmvXJrwq1eZl3c/4khlCPj+U5b7xH+ZCfDToR0ZY/wg0t39YcZmPTAXq9ic1AHG/BrpwYBZetFoCJOjWW9ExgM/YdLPh5hi2wRHHx8iO9O+2Fi6zuw8Ku/fVDp+0y9f97UCVMdpzFnVrEHYaoRhjMCD6YyOt9IgyUdJoOCXNQlexGg8dwIsZZF+7TTOAc6e8T9WAs8vs+w1d5lzRiG1kohxKRgskLfAMDrNSko392cHIwj1fHfyx6H5UaiShC2/v8FTtCh5usRCcRhStqsincjc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
